"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.nativeConstants = exports.QRCODE_TYPE = exports.QRCODE_LEVEL = exports.PRINT_TIMEOUT_MIN = exports.PRINT_TIMEOUT_MAX = exports.PRINTING_COMMANDS = exports.PRINTING_ALIGNMENT = exports.PRINTER_SERIES = exports.PRINTER_LANGUAGE = exports.FONT_A_CHARS_PER_LINE = exports.EPOS_MODE = exports.EPOS_HALFTONE = exports.EPOS_DRAWER_KICK_CONNECTOR = exports.EPOS_COLOR = exports.EPOS_BOOLEANS = exports.DEFAULT_PAPER_WIDTH = exports.DEFAULT_FONT_A_CHARS_PER_LINE = exports.BARCODE_TYPE = exports.BARCODE_HRI = void 0;
var _reactNative = require("react-native");
const {
  EscPosPrinter
} = _reactNative.NativeModules;
const nativeConstants = exports.nativeConstants = EscPosPrinter.getConstants();
const {
  EPOS2_TM_M10,
  EPOS2_TM_M30,
  EPOS2_TM_P20,
  EPOS2_TM_P60,
  EPOS2_TM_P60II,
  EPOS2_TM_P80,
  EPOS2_TM_T20,
  EPOS2_TM_T60,
  EPOS2_TM_T70,
  EPOS2_TM_T81,
  EPOS2_TM_T82,
  EPOS2_TM_T83,
  EPOS2_TM_T88,
  EPOS2_TM_T90,
  EPOS2_TM_T90KP,
  EPOS2_TM_U220,
  EPOS2_TM_U330,
  EPOS2_TM_L90,
  EPOS2_TM_H6000,
  EPOS2_TM_T83III,
  EPOS2_TM_T100,
  EPOS2_TM_M30II,
  EPOS2_TS_100,
  EPOS2_TM_M50,
  EPOS2_TM_T88VII,
  EPOS2_TM_L90LFC,
  EPOS2_TM_L100,
  COMMAND_ADD_TEXT,
  COMMAND_ADD_NEW_LINE,
  COMMAND_ADD_TEXT_STYLE,
  COMMAND_ADD_TEXT_SIZE,
  COMMAND_ADD_TEXT_SMOOTH,
  COMMAND_ADD_ALIGN,
  COMMAND_ADD_IMAGE,
  COMMAND_ADD_IMAGE_BASE_64,
  COMMAND_ADD_IMAGE_ASSET,
  COMMAND_ADD_BARCODE,
  COMMAND_ADD_QRCODE,
  COMMAND_ADD_CUT,
  COMMAND_ADD_DATA,
  COMMAND_ADD_PULSE,
  EPOS2_ALIGN_LEFT,
  EPOS2_ALIGN_RIGHT,
  EPOS2_ALIGN_CENTER,
  EPOS2_TRUE,
  EPOS2_FALSE,
  EPOS2_LANG_EN,
  EPOS2_LANG_JA,
  EPOS2_LANG_ZH_CN,
  EPOS2_LANG_ZH_TW,
  EPOS2_LANG_KO,
  EPOS2_LANG_TH,
  EPOS2_LANG_VI,
  EPOS2_LANG_MULTI,
  EPOS2_HRI_NONE,
  EPOS2_HRI_ABOVE,
  EPOS2_HRI_BELOW,
  EPOS2_HRI_BOTH,
  EPOS2_BARCODE_UPC_A,
  EPOS2_BARCODE_UPC_E,
  EPOS2_BARCODE_EAN13,
  EPOS2_BARCODE_JAN13,
  EPOS2_BARCODE_EAN8,
  EPOS2_BARCODE_JAN8,
  EPOS2_BARCODE_CODE39,
  EPOS2_BARCODE_ITF,
  EPOS2_BARCODE_CODABAR,
  EPOS2_BARCODE_CODE93,
  EPOS2_BARCODE_CODE128,
  EPOS2_BARCODE_GS1_128,
  EPOS2_BARCODE_GS1_DATABAR_OMNIDIRECTIONAL,
  EPOS2_BARCODE_GS1_DATABAR_TRUNCATED,
  EPOS2_BARCODE_GS1_DATABAR_LIMITED,
  EPOS2_BARCODE_GS1_DATABAR_EXPANDED,
  EPOS2_BARCODE_CODE128_AUTO,
  EPOS2_SYMBOL_QRCODE_MODEL_1,
  EPOS2_SYMBOL_QRCODE_MODEL_2,
  EPOS2_SYMBOL_QRCODE_MICRO,
  EPOS2_LEVEL_L,
  EPOS2_LEVEL_M,
  EPOS2_LEVEL_Q,
  EPOS2_LEVEL_H,
  EPOS2_COLOR_1,
  EPOS2_COLOR_2,
  EPOS2_COLOR_3,
  EPOS2_COLOR_4,
  EPOS2_MODE_MONO,
  EPOS2_MODE_GRAY16,
  EPOS2_MODE_MONO_HIGH_DENSITY,
  EPOS2_HALFTONE_DITHER,
  EPOS2_HALFTONE_ERROR_DIFFUSION,
  EPOS2_HALFTONE_THRESHOLD,
  EPOS2_DRAWER_2PIN,
  EPOS2_DRAWER_5PIN
} = nativeConstants;
const PRINTING_COMMANDS = exports.PRINTING_COMMANDS = {
  COMMAND_ADD_TEXT,
  COMMAND_ADD_NEW_LINE,
  COMMAND_ADD_TEXT_STYLE,
  COMMAND_ADD_TEXT_SIZE,
  COMMAND_ADD_TEXT_SMOOTH,
  COMMAND_ADD_ALIGN,
  COMMAND_ADD_IMAGE,
  COMMAND_ADD_IMAGE_BASE_64,
  COMMAND_ADD_IMAGE_ASSET,
  COMMAND_ADD_BARCODE,
  COMMAND_ADD_QRCODE,
  COMMAND_ADD_CUT,
  COMMAND_ADD_DATA,
  COMMAND_ADD_PULSE
};
const EPOS_BOOLEANS = exports.EPOS_BOOLEANS = {
  EPOS2_TRUE,
  EPOS2_FALSE
};
const PRINTING_ALIGNMENT = exports.PRINTING_ALIGNMENT = {
  left: EPOS2_ALIGN_LEFT,
  right: EPOS2_ALIGN_RIGHT,
  center: EPOS2_ALIGN_CENTER
};
const PRINTER_SERIES = exports.PRINTER_SERIES = {
  EPOS2_TM_M10,
  EPOS2_TM_M30,
  EPOS2_TM_P20,
  EPOS2_TM_P60,
  EPOS2_TM_P60II,
  EPOS2_TM_P80,
  EPOS2_TM_T20,
  EPOS2_TM_T60,
  EPOS2_TM_T70,
  EPOS2_TM_T81,
  EPOS2_TM_T82,
  EPOS2_TM_T83,
  EPOS2_TM_T88,
  EPOS2_TM_T90,
  EPOS2_TM_T90KP,
  EPOS2_TM_U220,
  EPOS2_TM_U330,
  EPOS2_TM_L90,
  EPOS2_TM_H6000,
  EPOS2_TM_T83III,
  EPOS2_TM_T100,
  EPOS2_TM_M30II,
  EPOS2_TS_100,
  EPOS2_TM_M50,
  EPOS2_TM_T88VII,
  EPOS2_TM_L90LFC,
  EPOS2_TM_L100
};
const FONT_A_CHARS_PER_LINE = exports.FONT_A_CHARS_PER_LINE = {
  EPOS2_TM_M10: {
    58: 35,
    60: 35
  },
  EPOS2_TM_M30: {
    80: 48,
    58: 35,
    60: 35
  },
  EPOS2_TM_M30II: {
    80: 42,
    58: 32,
    60: 32
  },
  EPOS2_TM_P20: {
    58: 32,
    60: 35
  },
  EPOS2_TM_P60: {
    58: 35,
    60: 35
  },
  EPOS2_TM_P60II: {
    58: 35,
    60: 36
  },
  EPOS2_TM_P80: {
    80: 42
  },
  EPOS2_TM_T20: {
    80: 48,
    58: 35,
    60: 35
  },
  EPOS2_TM_T60: {
    80: 42
  },
  EPOS2_TM_T70: {
    80: 42
  },
  EPOS2_TM_T81: {
    80: 42
  },
  EPOS2_TM_T82: {
    80: 48,
    58: 35,
    60: 35
  },
  EPOS2_TM_T83: {
    80: 42
  },
  EPOS2_TM_T83III: {
    80: 42
  },
  EPOS2_TM_T88: {
    80: 42,
    58: 30,
    60: 30
  },
  EPOS2_TM_T90: {
    80: 42,
    60: 30,
    58: 30
  },
  EPOS2_TM_T100: {
    80: 42
  },
  EPOS2_TM_U220: {
    80: 35,
    58: 27,
    60: 27
  },
  EPOS2_TM_U330: {
    80: 33,
    58: 25,
    60: 25
  },
  EPOS2_TM_L90: {
    80: 42,
    58: 30,
    60: 30
  },
  EPOS2_TM_H6000: {
    80: 42,
    58: 30,
    60: 30
  }
};
const DEFAULT_FONT_A_CHARS_PER_LINE = exports.DEFAULT_FONT_A_CHARS_PER_LINE = {
  80: 42,
  58: 30,
  60: 30
};
const DEFAULT_PAPER_WIDTH = exports.DEFAULT_PAPER_WIDTH = 60;
const PRINTER_LANGUAGE = exports.PRINTER_LANGUAGE = {
  EPOS2_LANG_EN,
  EPOS2_LANG_JA,
  EPOS2_LANG_ZH_CN,
  EPOS2_LANG_ZH_TW,
  EPOS2_LANG_KO,
  EPOS2_LANG_TH,
  EPOS2_LANG_VI,
  EPOS2_LANG_MULTI
};
const BARCODE_TYPE = exports.BARCODE_TYPE = {
  EPOS2_BARCODE_UPC_A,
  EPOS2_BARCODE_UPC_E,
  EPOS2_BARCODE_EAN13,
  EPOS2_BARCODE_JAN13,
  EPOS2_BARCODE_EAN8,
  EPOS2_BARCODE_JAN8,
  EPOS2_BARCODE_CODE39,
  EPOS2_BARCODE_ITF,
  EPOS2_BARCODE_CODABAR,
  EPOS2_BARCODE_CODE93,
  EPOS2_BARCODE_CODE128,
  EPOS2_BARCODE_GS1_128,
  EPOS2_BARCODE_GS1_DATABAR_OMNIDIRECTIONAL,
  EPOS2_BARCODE_GS1_DATABAR_TRUNCATED,
  EPOS2_BARCODE_GS1_DATABAR_LIMITED,
  EPOS2_BARCODE_GS1_DATABAR_EXPANDED,
  EPOS2_BARCODE_CODE128_AUTO
};
const BARCODE_HRI = exports.BARCODE_HRI = {
  EPOS2_HRI_NONE,
  EPOS2_HRI_ABOVE,
  EPOS2_HRI_BELOW,
  EPOS2_HRI_BOTH
};
const QRCODE_TYPE = exports.QRCODE_TYPE = {
  EPOS2_SYMBOL_QRCODE_MODEL_1,
  EPOS2_SYMBOL_QRCODE_MODEL_2,
  EPOS2_SYMBOL_QRCODE_MICRO
};
const QRCODE_LEVEL = exports.QRCODE_LEVEL = {
  EPOS2_LEVEL_L,
  EPOS2_LEVEL_M,
  EPOS2_LEVEL_Q,
  EPOS2_LEVEL_H
};
const EPOS_COLOR = exports.EPOS_COLOR = {
  EPOS2_COLOR_1,
  EPOS2_COLOR_2,
  EPOS2_COLOR_3,
  EPOS2_COLOR_4
};
const EPOS_MODE = exports.EPOS_MODE = {
  EPOS2_MODE_MONO,
  EPOS2_MODE_GRAY16,
  EPOS2_MODE_MONO_HIGH_DENSITY
};
const EPOS_HALFTONE = exports.EPOS_HALFTONE = {
  EPOS2_HALFTONE_DITHER,
  EPOS2_HALFTONE_ERROR_DIFFUSION,
  EPOS2_HALFTONE_THRESHOLD
};
const EPOS_DRAWER_KICK_CONNECTOR = exports.EPOS_DRAWER_KICK_CONNECTOR = {
  EPOS2_DRAWER_2PIN,
  EPOS2_DRAWER_5PIN
};
const PRINT_TIMEOUT_MIN = exports.PRINT_TIMEOUT_MIN = 5000;
const PRINT_TIMEOUT_MAX = exports.PRINT_TIMEOUT_MAX = 600000;
//# sourceMappingURL=constants.js.map